const router = require('express').Router();
const { protect, authorize } = require('../middleware/auth.middleware');
const { create, list, toggle, remove, trigger } = require('../controllers/automation.controller');
const admin = authorize('super_admin', 'school_admin');
const staff = authorize('super_admin', 'school_admin', 'teacher');
router.post('/', protect, admin, create);
router.post('/trigger', protect, staff, trigger);
router.get('/:school_id', protect, admin, list);
router.put('/:id/toggle', protect, admin, toggle);
router.delete('/:id', protect, admin, remove);
module.exports = router;
