const router = require('express').Router();
const { protect, authorize } = require('../middleware/auth.middleware');
const { create, list, link, unlink, byCourse, award, studentCompetencies, remove } = require('../controllers/competency.controller');
const admin = authorize('super_admin', 'school_admin');
const staff = authorize('super_admin', 'school_admin', 'teacher');
router.post('/', protect, admin, create);
router.get('/school/:school_id', protect, list);
router.post('/link', protect, staff, link);
router.delete('/link/:course_id/:competency_id', protect, staff, unlink);
router.get('/course/:course_id', protect, byCourse);
router.post('/award', protect, staff, award);
router.get('/student/:student_id', protect, studentCompetencies);
router.delete('/:id', protect, admin, remove);
module.exports = router;
