const router = require('express').Router();
const { protect } = require('../middleware/auth.middleware');
const { createPath, addCourse, list, removeCourse, removePath, checkUnlock } = require('../controllers/learningpath.controller');
router.post('/', protect, createPath);
router.post('/course', protect, addCourse);
router.get('/:school_id', protect, list);
router.delete('/:path_id/course/:course_id', protect, removeCourse);
router.delete('/:id', protect, removePath);
router.get('/unlock/:student_id/:path_id/:course_id', protect, checkUnlock);
module.exports = router;
