const router = require('express').Router();
const { protect } = require('../middleware/auth.middleware');
const { createTask, listTasks, submit, review, listSubmissions, studentSubmissions } = require('../controllers/proofofwork.controller');
router.post('/tasks', protect, createTask);
router.get('/tasks/:course_id', protect, listTasks);
router.post('/submit', protect, submit);
router.put('/review', protect, review);
router.get('/submissions/:task_id', protect, listSubmissions);
router.get('/student/:student_id', protect, studentSubmissions);
module.exports = router;
